set -g mouse on

set -g monitor-activity on
set -g bell-action any
set -g visual-activity on
set -g visual-bell off

set -g window-status-activity-style "bold,underscore,fg=yellow"
set -g window-status-bell-style "bold,reverse,fg=red"

bind-key C-l display-message "Clearing marks" \; set -g monitor-activity off \; set -g monitor-activity on
set -g set-titles on
set -g set-titles-string "tmux:#S · #W"
bind-key a last-window
