# ----- True color support (required for Textual sidebar) -----
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g mouse on
set -g status off

# ----- Misc -----
set -g set-titles on
set -g set-titles-string "tmux:#S · #W"
bind-key a last-window
